# docker compose file
# build and run the container in the ../site directory
version: "3"
services:
  nginx-site:
    build:
      context: ../../apps/nginx-site
      dockerfile: Dockerfile

    # map external port 8080 to internal port 8080
    ports:
      - "8080:8080"

  caddy-site:
    build:
      context: ../../apps/caddy-site
      dockerfile: Dockerfile

    # map external port 8081 to internal port 8080
    ports:
      - "8081:8080"

  go-time:
    build:
      context: ../../apps/go-time
      dockerfile: Dockerfile

    # map external port 8082 to internal port 8080
    ports:
      - "8082:8080"

  deno-time:
    build:
      context: ../../apps/deno-time
      dockerfile: Dockerfile

    # map external port 8083 to internal port 8080
    ports:
      - "8083:8080"

  # Replace this with a flask example
  # django-time:
  #   build:
  #     context: ../../apps/django-time
  #     dockerfile: Dockerfile

  #   # map external port 8084 to internal port 8080
  #   ports:
  #     - "8084:8080"
