# docker compose file
# build and run the container in the ../site directory
version: "3"
services:
  site-nextra:
    build:
      context: ../..
      args:
        - service=site
      # progress: plain
      dockerfile: Dockerfile.pnpm-workspace.nextjs
    # Run an init inside the container that forwards signals and reaps processes. replaces tini
    init: true
    # map external port 8081 to internal port 8080
    ports:
      - "8080:8080"
  site-nginx:
    build:
      context: ../../apps/site-nginx
      dockerfile: Dockerfile

    # map external port 8080 to internal port 8080
    ports:
      - "8081:8080"

  site-caddy:
    build:
      context: ../../apps/site-caddy
      dockerfile: Dockerfile

    # map external port 8081 to internal port 8080
    ports:
      - "8082:8080"

  time-go:
    build:
      context: ../../apps/time-go
      dockerfile: Dockerfile

    # map external port 8082 to internal port 8080
    ports:
      - "8083:8080"

  time-deno:
    build:
      context: ../../apps/time-deno
      dockerfile: Dockerfile

    # map external port 8083 to internal port 8080
    ports:
      - "8084:8080"

  # Add a flask example
